[versions]
agp = "9.0.1"
aboutlibraries = "14.0.0-b02"
kotlin = "2.3.10"
google-services = "4.4.4"
google-firebase-crashlytics = "3.0.6"
media3 = "1.9.2"
junittest = "3.7.0"
mannodermaus = "2.0.1"
mockk = "1.14.9"
jupiter = "6.0.3"
testCorutines = "1.10.2"
testTurbine = "1.2.1"
truth = "1.7.0"
testManifestTestJunit4Android = "1.10.3"
slf4j = "2.0.17"
ktor = "3.4.0"

[libraries]
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }

# --- TESTING ---
# Unit Tests (test folder)
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }
mockk-api = { module = "io.mockk:mockk", version.ref = "mockk" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "testCorutines" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "testTurbine" }
androidx-truth = { module = "androidx.test.ext:truth", version.ref = "truth" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

# Instrumentation Tests (androidTest folder)
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "junittest" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "testManifestTestJunit4Android" }
androidx-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "testManifestTestJunit4Android" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutlibraries" }
googlePlayServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
googleFirebase = { id = "com.google.firebase.crashlytics", version.ref = "google-firebase-crashlytics" }
mannodermaus = { id = "de.mannodermaus.android-junit5", version.ref = "mannodermaus" }

[bundles]
media3 = [
    "media3-exoplayer",
    "media3-ui",
    "media3-session",
]
# For local tests on the JVM (test sourceSet)
unitTest = [
    "jupiter-api",
    "jupiter-params",
    "mockk-api",
    "test-kotlin-coroutines",
    "test-turbine",
    "androidx-truth",
    "slf4j-simple",
    "ktor-client-mock"
]
unitTestRuntime = ["jupiter-engine"]

# For instrumentation tests on an Android device (androidTest sourceSet)
instrumentationTest = [
    "jupiter-api",
    "jupiter-params",
    "mockk-android",
    "test-kotlin-coroutines",
    "test-turbine",
    "androidx-espresso-core",
    "androidx-ui-test-junit4-android",
    "androidx-truth",
]